import { BarChart3, BookOpen, CalendarCheck, ChevronRight, GraduationCap, LayoutDashboard, LogOut, Menu, Plus, Save, School, UsersRound, X } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import Logo from '../components/Logo'
import { schoolApi } from '../lib/api'

const nav = [[LayoutDashboard,'Overview','overview'],[UsersRound,'Students','students','tenant'],[BookOpen,'Classes','classes','tenant'],[CalendarCheck,'Attendance','attendance','tenant'],[School,'Schools','schools','super'],[BarChart3,'Users','users']]
const today = new Date().toISOString().slice(0,10)

export default function DashboardPage({ session, onLogout }) {
  const [page,setPage]=useState('overview'), [mobile,setMobile]=useState(false), [data,setData]=useState(null), [error,setError]=useState(''), [loading,setLoading]=useState(false)
  const [formOpen,setFormOpen]=useState(false), [notice,setNotice]=useState('')
  const user=session?.user || {}; const isSuper=user.role==='super_admin'
  const load=useCallback(async()=>{ setLoading(true); setError(''); try { let result; if(page==='students') result=await schoolApi.students(); else if(page==='classes') result=await schoolApi.classes(); else if(page==='schools') result=await schoolApi.schools(); else if(page==='users') result=await schoolApi.users(isSuper); else if(page==='attendance') result=await schoolApi.attendance(today); else result=await schoolApi.dashboard(); setData(result) } catch(e){ setError(e.message) } finally{setLoading(false)} },[page,isSuper])
  useEffect(()=>{ const timer=setTimeout(load,0); return ()=>clearTimeout(timer) },[load])
  const lists={students:data?.data||[],classes:data?.data||[],schools:data?.schools||[],users:data?.users||[],attendance:data?.data||[]}
  function moveTo(key){setPage(key);setMobile(false);setFormOpen(false)}
  const canCreate=['School Admin','Teacher'].includes(user.role)
  return <div className="app-shell"><aside className={mobile?'sidebar open':'sidebar'}><div className="sidebar-head"><Logo /><button onClick={()=>setMobile(false)}><X /></button></div><nav>{nav.filter(([, , ,scope])=>scope!=='super'||isSuper).filter(([, , ,scope])=>scope!=='tenant'||!isSuper).map(([Icon,label,key])=><button key={key} className={page===key?'active':''} onClick={()=>moveTo(key)}><Icon />{label}<ChevronRight /></button>)}</nav><div className="profile-card"><span>{(user.name||'U').slice(0,2).toUpperCase()}</span><div><b>{user.name||'School user'}</b><small>{user.role||'Member'}</small></div><button onClick={onLogout} title="Log out"><LogOut /></button></div></aside>{mobile&&<button className="sidebar-backdrop" onClick={()=>setMobile(false)} />}
    <main className="dashboard-main"><header className="dashboard-header"><button className="mobile-nav" onClick={()=>setMobile(true)}><Menu /></button><div><small>{user.school_name||'EduFlow workspace'}</small><h1>{nav.find(n=>n[2]===page)?.[1]}</h1></div><div className="header-user"><span>{(user.name||'U').charAt(0)}</span><div><b>{user.name}</b><small>{user.role}</small></div></div></header>
      <div className="dashboard-content">{error&&<div className="api-notice"><b>Could not load this page.</b><span>{error}</span><button onClick={load}>Try again</button></div>}{notice&&<div className="success-notice">{notice}</div>}{loading?<div className="loading-grid"><i/><i/><i/></div>:page==='overview'?<Overview data={data} isSuper={isSuper}/>:page==='attendance'?<Attendance initialData={data} setError={setError} setNotice={setNotice}/>:<><PageActions page={page} canCreate={canCreate||isSuper} open={formOpen} setOpen={setFormOpen}/>{formOpen&&page==='students'&&<StudentForm onDone={message=>{setNotice(message);setFormOpen(false);load()}}/>}{formOpen&&page==='classes'&&<ClassForm onDone={message=>{setNotice(message);setFormOpen(false);load()}}/>}{formOpen&&page==='schools'&&<SchoolForm onDone={message=>{setNotice(message);setFormOpen(false);load()}}/>}<DataList type={page} rows={lists[page]}/></>}</div></main></div>
}

function Overview({data,isSuper}) { const stats=data?.stats||{}; const cards=isSuper?[['Schools',stats.total_schools??0,'registered'],['Active schools',stats.active_schools??0,'currently active'],['Users',stats.total_users??0,'across all schools'],['School admins',stats.total_admins??0,'administrators']]:[['Students',stats.total_students??0,'enrolled'],['Teachers',stats.total_teachers??0,'team members'],['Classes',stats.total_classes??0,'active classes'],['Attendance',stats.attendance_percentage??'—','today']]; return <><section className="welcome-card"><div><span>Good to see you</span><h2>{isSuper?'Your school network, clearly organized.':'Your school, clearly organized.'}</h2><p>{isSuper?'System-wide information from every registered school.':'Live information from your Flask API appears here as your school grows.'}</p></div><GraduationCap /></section><div className="stat-grid">{cards.map(([a,b,c])=><article key={a}><small>{a}</small><b>{b}{a==='Attendance'&&b!=='—'?'%':''}</b><span>{c}</span></article>)}</div><section className="empty-panel"><CalendarCheck/><div><h3>Everything starts here</h3><p>{isSuper?'Use Schools and Users to manage your complete network.':'Use the navigation to view live students, classes, users and attendance records.'}</p></div></section></> }
function DataList({type,rows}) { const title=type.charAt(0).toUpperCase()+type.slice(1); return <section className="data-panel"><div className="panel-title"><div><span>Connected to Flask API</span><h2>{title} directory</h2></div><b>{rows.length} records</b></div>{rows.length===0?<div className="empty-state"><UsersRound/><h3>No {type} found</h3><p>New records created through the API will appear here.</p></div>:<div className="table-wrap"><table><thead><tr><th>Name / title</th><th>Details</th><th>Status</th></tr></thead><tbody>{rows.map((row,i)=><tr key={row.id??i}><td><b>{row.first_name ? `${row.first_name} ${row.last_name||''}` : row.class_name||row.name||row.schoolName||row.domain||`Record ${i+1}`}</b><small>{row.email||row.admission_no||row.description||''}</small></td><td>{row.role||row.section||row.domain||row.plan_setup||'—'}</td><td><span className="status-pill">{row.status||'Active'}</span></td></tr>)}</tbody></table></div>}</section> }
function PageActions({page,canCreate,open,setOpen}) { if(!canCreate||!['students','classes','schools'].includes(page)) return null; const label=page==='students'?'student':page==='classes'?'class':'school'; return <div className="page-actions"><p>Add new records directly to your school API.</p><button className="button button-small" onClick={()=>setOpen(!open)}>{open?<X size={17}/>:<Plus size={17}/>} {open?'Close form':`Add ${label}`}</button></div> }

function SchoolForm({onDone}) { const [values,setValues]=useState({schoolName:'',domain:'',adminEmail:'',planSetup:'Standard',logo:null}),[busy,setBusy]=useState(false),[error,setError]=useState(''); const field=(name,value)=>setValues({...values,[name]:value}); async function submit(e){e.preventDefault();setBusy(true);setError('');try{const result=await schoolApi.createSchool(values);onDone(result.message||'School onboarded successfully.')}catch(err){setError(err.message)}finally{setBusy(false)}} return <form className="editor-card" onSubmit={submit}><div className="editor-heading"><School/><div><h3>Onboard a school</h3><p>Create its tenant workspace and register it in the central system.</p></div></div><div className="field-grid"><label>School name *<input required value={values.schoolName} onChange={e=>field('schoolName',e.target.value)} placeholder="Green Valley School"/></label><label>Unique domain *<input required value={values.domain} onChange={e=>field('domain',e.target.value.toLowerCase().replace(/\s+/g,'-'))} placeholder="green-valley"/><small className="field-help">Used by staff when signing in.</small></label><label>Administrator email *<input required type="email" value={values.adminEmail} onChange={e=>field('adminEmail',e.target.value)} placeholder="admin@school.com"/></label><label>Plan *<select value={values.planSetup} onChange={e=>field('planSetup',e.target.value)}><option>Standard</option><option>Premium</option><option>Enterprise</option><option>Trial</option></select></label><label className="wide">School logo *<input required type="file" accept=".png,.jpg,.jpeg,image/png,image/jpeg" onChange={e=>field('logo',e.target.files[0])}/><small className="field-help">PNG, JPG or JPEG.</small></label></div>{error&&<div className="form-error">{error}</div>}<button className="button button-small" disabled={busy}><Save size={16}/>{busy?'Creating school…':'Onboard school'}</button></form> }

function ClassForm({onDone}) { const [values,setValues]=useState({class_name:'',description:''}),[busy,setBusy]=useState(false),[error,setError]=useState(''); async function submit(e){e.preventDefault();setBusy(true);setError('');try{const result=await schoolApi.createClass(values);onDone(result.message||'Class created successfully.')}catch(err){setError(err.message)}finally{setBusy(false)}} return <form className="editor-card" onSubmit={submit}><div className="editor-heading"><BookOpen/><div><h3>Create a class</h3><p>Add a class to the current school workspace.</p></div></div><div className="field-grid"><label>Class name<input required value={values.class_name} onChange={e=>setValues({...values,class_name:e.target.value})} placeholder="Example: Grade 8"/></label><label>Description<input value={values.description} onChange={e=>setValues({...values,description:e.target.value})} placeholder="Optional class description"/></label></div>{error&&<div className="form-error">{error}</div>}<button className="button button-small" disabled={busy}><Save size={16}/>{busy?'Creating…':'Create class'}</button></form> }

function StudentForm({onDone}) { const empty={admission_no:'',first_name:'',last_name:'',gender:'',dob:'',mobile:'',email:'',father_name:'',mother_name:'',class_name:'',section:'',address:'',photo:null}; const [values,setValues]=useState(empty),[busy,setBusy]=useState(false),[error,setError]=useState(''); const field=(name,value)=>setValues({...values,[name]:value}); async function submit(e){e.preventDefault();setBusy(true);setError('');try{const result=await schoolApi.createStudent(values);onDone(result.message||'Student registered successfully.')}catch(err){setError(err.message)}finally{setBusy(false)}} return <form className="editor-card" onSubmit={submit}><div className="editor-heading"><UsersRound/><div><h3>Register a student</h3><p>Fields marked with * are required by the Flask API.</p></div></div><div className="field-grid three"><label>Admission number *<input required value={values.admission_no} onChange={e=>field('admission_no',e.target.value)} /></label><label>First name *<input required value={values.first_name} onChange={e=>field('first_name',e.target.value)} /></label><label>Last name<input value={values.last_name} onChange={e=>field('last_name',e.target.value)} /></label><label>Class *<input required value={values.class_name} onChange={e=>field('class_name',e.target.value)} placeholder="Grade 8" /></label><label>Section *<input required value={values.section} onChange={e=>field('section',e.target.value)} placeholder="A" /></label><label>Gender<select value={values.gender} onChange={e=>field('gender',e.target.value)}><option value="">Select</option><option>Male</option><option>Female</option><option>Other</option></select></label><label>Date of birth<input type="date" value={values.dob} onChange={e=>field('dob',e.target.value)} /></label><label>Mobile<input value={values.mobile} onChange={e=>field('mobile',e.target.value)} /></label><label>Email<input type="email" value={values.email} onChange={e=>field('email',e.target.value)} /></label><label>Father name<input value={values.father_name} onChange={e=>field('father_name',e.target.value)} /></label><label>Mother name<input value={values.mother_name} onChange={e=>field('mother_name',e.target.value)} /></label><label>Photo<input type="file" accept="image/*" onChange={e=>field('photo',e.target.files[0])} /></label><label className="wide">Address<textarea value={values.address} onChange={e=>field('address',e.target.value)} rows="2" /></label></div>{error&&<div className="form-error">{error}</div>}<button className="button button-small" disabled={busy}><Save size={16}/>{busy?'Registering…':'Register student'}</button></form> }

function Attendance({initialData,setError,setNotice}) { const [data,setData]=useState(initialData),[date,setDate]=useState(today),[className,setClassName]=useState('All'),[section,setSection]=useState('All'),[busy,setBusy]=useState(false); const s=data?.summary||{},rows=data?.data||[]; async function filter(e){e.preventDefault();setBusy(true);setError('');try{setData(await schoolApi.attendance(date,className,section))}catch(err){setError(err.message)}finally{setBusy(false)}} function changeStatus(id,status){setData({...data,data:rows.map(r=>r.student_id===id?{...r,status}:r)})} async function save(){setBusy(true);setError('');try{const result=await schoolApi.markAttendance({attendance_date:date,class_name:className==='All'?(rows[0]?.class_name||'All'):className,section:section==='All'?(rows[0]?.section||'All'):section,students:rows.map(r=>({student_id:r.student_id,student_name:r.student_name,status:r.status||'Present',remarks:r.remarks||''}))});setNotice(result.message||'Attendance saved successfully.');setData(await schoolApi.attendance(date,className,section))}catch(err){setError(err.message)}finally{setBusy(false)}} return <><form className="attendance-filter" onSubmit={filter}><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><label>Class<input value={className} onChange={e=>setClassName(e.target.value)} placeholder="All"/></label><label>Section<input value={section} onChange={e=>setSection(e.target.value)} placeholder="All"/></label><button className="button button-small" disabled={busy}>{busy?'Loading…':'Load students'}</button></form><div className="stat-grid compact">{[['Students',s.total_students??rows.length],['Present',rows.filter(r=>r.status==='Present').length],['Absent',rows.filter(r=>r.status==='Absent').length],['Pending',rows.filter(r=>!r.status).length]].map(([a,b])=><article key={a}><small>{a}</small><b>{b}</b><span>{date}</span></article>)}</div><section className="data-panel"><div className="panel-title"><div><span>Daily register</span><h2>Mark attendance</h2></div>{rows.length>0&&<button className="button button-small" onClick={save} disabled={busy}><Save size={16}/>{busy?'Saving…':'Save attendance'}</button>}</div>{rows.length===0?<div className="empty-state"><CalendarCheck/><h3>No students found</h3><p>Choose a class and section, then load students.</p></div>:<div className="attendance-list">{rows.map(row=><div className="attendance-row" key={row.student_id}><div><b>{row.student_name}</b><small>{row.admission_no} · {row.class_name} {row.section}</small></div><div className="status-options"><button className={row.status==='Present'?'present active':'present'} onClick={()=>changeStatus(row.student_id,'Present')}>Present</button><button className={row.status==='Absent'?'absent active':'absent'} onClick={()=>changeStatus(row.student_id,'Absent')}>Absent</button></div></div>)}</div>}</section></>}
