import { ArrowLeft, Eye, EyeOff, LockKeyhole, Mail, School } from 'lucide-react'
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import Logo from '../components/Logo'
import { schoolApi } from '../lib/api'

export default function LoginPage({ onLogin }) {
  const navigate = useNavigate(); const [superAdmin, setSuperAdmin] = useState(false); const [show, setShow] = useState(false)
  const [form, setForm] = useState({ email: '', password: '', school_domain: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const change = e => setForm({ ...form, [e.target.name]: e.target.value })
  async function submit(e) { e.preventDefault(); setError(''); setBusy(true); try { const data = superAdmin ? await schoolApi.superAdminLogin({email:form.email,password:form.password}) : await schoolApi.schoolLogin(form); onLogin(data); navigate('/dashboard') } catch (err) { setError(err.message) } finally { setBusy(false) } }
  return <main className="login-page"><section className="login-aside"><Link to="/"><Logo light /></Link><div><span className="eyebrow eyebrow-dark">Built for better school days</span><h1>Welcome back to your school community.</h1><p>One secure place for your people, classes and daily progress.</p></div><small>Simple. Connected. Thoughtful.</small></section><section className="login-panel"><div className="login-box"><Link className="back-link" to="/"><ArrowLeft size={17} /> Back to home</Link><div className="login-heading"><span className="login-icon"><LockKeyhole /></span><h2>Sign in to EduFlow</h2><p>Use the details provided by your school.</p></div><div className="login-tabs"><button className={!superAdmin ? 'active' : ''} onClick={() => setSuperAdmin(false)}>School user</button><button className={superAdmin ? 'active' : ''} onClick={() => setSuperAdmin(true)}>Super admin</button></div><form onSubmit={submit} className="form-stack">{!superAdmin && <label>School domain<div className="input-wrap"><School /><input name="school_domain" value={form.school_domain} onChange={change} placeholder="your-school" required /></div></label>}<label>Email address<div className="input-wrap"><Mail /><input type="email" name="email" value={form.email} onChange={change} placeholder="name@school.com" required /></div></label><label>Password<div className="input-wrap"><LockKeyhole /><input type={show ? 'text' : 'password'} name="password" value={form.password} onChange={change} placeholder="Enter your password" required /><button type="button" onClick={() => setShow(!show)}>{show ? <EyeOff /> : <Eye />}</button></div></label>{error && <div className="form-error">{error}</div>}<button className="button button-full" disabled={busy}>{busy ? 'Signing in…' : 'Sign in securely'}</button></form><p className="login-help">Need access? Contact your school administrator.</p></div></section></main>
}
