import { BookCheck, ClipboardCheck, Plus, Save, Send } from 'lucide-react'
import { useEffect, useState } from 'react'
import { schoolApi } from '../lib/api'
import { confirmPopup } from '../lib/confirmPopup'

const localDateTime = () => new Date(Date.now() + 86400000 - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 16)
const empty = { title: '', description: '', class_id: '', subject_id: '', due_at: localDateTime(), max_score: 100 }

export default function AssignmentManagement() {
  const [assignments, setAssignments] = useState([]), [classes, setClasses] = useState([]), [subjects, setSubjects] = useState([])
  const [form, setForm] = useState(empty), [selected, setSelected] = useState(null), [students, setStudents] = useState([])
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [message, setMessage] = useState('')
  async function load() { setBusy(true); setError(''); try { const [a, b, c] = await Promise.all([schoolApi.assignments(), schoolApi.classes(), schoolApi.subjects()]); setAssignments(a.data || []); setClasses((b.data || []).filter(x => x.status === 'active')); setSubjects((c.data || []).filter(x => x.status === 'active')) } catch (e) { setError(e.message) } finally { setBusy(false) } }
  useEffect(() => { const timer = setTimeout(load, 0); return () => clearTimeout(timer) }, [])
  const field = (name, value) => setForm(current => ({ ...current, [name]: value }))
  async function create(event) { event.preventDefault(); setBusy(true); setError(''); try { const result = await schoolApi.createAssignment({ ...form, class_id: Number(form.class_id), subject_id: Number(form.subject_id), max_score: Number(form.max_score), due_at: new Date(form.due_at).toISOString() }); setMessage(result.message); setForm(empty); await load() } catch (e) { setError(e.message) } finally { setBusy(false) } }
  async function open(item) { setBusy(true); setError(''); setSelected(item); try { const result = await schoolApi.assignmentStudents(item.id); setStudents((result.data || []).map(x => ({ ...x, content: x.content || '', attachment_url: x.attachment_url || '', score: x.score ?? '', feedback: x.feedback || '' }))) } catch (e) { setError(e.message) } finally { setBusy(false) } }
  async function status(item, value) { if (!await confirmPopup({ title: `${value} ${item.title}?`, message: value === 'published' ? 'Students can submit after publication.' : 'This changes assignment availability.', confirmLabel: value, tone: 'primary' })) return; setBusy(true); try { const result = await schoolApi.changeAssignmentStatus(item.id, value); setMessage(result.message); await load(); setSelected(null); setStudents([]) } catch (e) { setError(e.message) } finally { setBusy(false) } }
  function editStudent(index, name, value) { setStudents(current => current.map((x, i) => i === index ? { ...x, [name]: value } : x)) }
  async function submitHomework(item) { setBusy(true); setError(''); try { const result = await schoolApi.saveAssignmentSubmission(selected.id, { student_id: item.student_id, content: item.content, attachment_url: item.attachment_url }); setMessage(result.message); await open(selected) } catch (e) { setError(e.message) } finally { setBusy(false) } }
  async function grade(item) { setBusy(true); setError(''); try { const result = await schoolApi.gradeAssignmentSubmission(selected.id, item.student_id, { score: Number(item.score), feedback: item.feedback }); setMessage(result.message); await open(selected); await load() } catch (e) { setError(e.message) } finally { setBusy(false) } }
  return <div className="assignment-management">
    <form className="editor-card" onSubmit={create}><div className="editor-heading"><Plus /><div><h3>Create assignment</h3><p>Prepare class homework and publish it when ready.</p></div></div><div className="field-grid three"><label>Title *<input required maxLength="180" value={form.title} onChange={e => field('title', e.target.value)} /></label><label>Class *<select required value={form.class_id} onChange={e => field('class_id', e.target.value)}><option value="">Select class</option>{classes.map(x => <option key={x.id} value={x.id}>{x.class_name}</option>)}</select></label><label>Subject *<select required value={form.subject_id} onChange={e => field('subject_id', e.target.value)}><option value="">Select subject</option>{subjects.map(x => <option key={x.id} value={x.id}>{x.code} - {x.name}</option>)}</select></label><label>Due date and time *<input required type="datetime-local" value={form.due_at} onChange={e => field('due_at', e.target.value)} /></label><label>Maximum score *<input required type="number" min="1" step="0.01" value={form.max_score} onChange={e => field('max_score', e.target.value)} /></label><label className="wide">Instructions *<textarea required rows="3" value={form.description} onChange={e => field('description', e.target.value)} /></label></div><button className="button button-small" disabled={busy}><Plus />Create draft</button></form>
    {error && <div className="form-error">{error}</div>}{message && <div className="success-notice">{message}</div>}
    <section className="data-panel"><div className="panel-title"><div><span>Learning tasks</span><h2>Assignments and homework</h2></div><b>{assignments.length} assignments</b></div><div className="assignment-list">{assignments.map(item => <article key={item.id}><BookCheck /><div><b>{item.title}</b><small>{item.class_name} / {item.subject_name} / due {new Date(item.due_at).toLocaleString()}</small><p>{item.description}</p></div><span className={`delivery-status ${item.status}`}>{item.status}</span><em>{item.submission_count} submitted / {item.graded_count} graded</em><div className="student-row-actions"><button onClick={() => open(item)}><ClipboardCheck />Students</button>{item.status === 'draft' && <button onClick={() => status(item, 'published')}><Send />Publish</button>}{item.status === 'published' && <button onClick={() => status(item, 'closed')}>Close</button>}</div></article>)}</div>{assignments.length === 0 && <div className="empty-state"><BookCheck /><h3>No assignments found</h3><p>Create the first homework task.</p></div>}</section>
    {selected && <section className="data-panel"><div className="panel-title"><div><span>Submission register</span><h2>{selected.title}</h2></div><button className="refresh-button" onClick={() => { setSelected(null); setStudents([]) }}>Close</button></div><div className="assignment-students">{students.map((item, index) => <article key={item.student_id}><div><b>{item.student_name}</b><small>{item.admission_no} / {item.status || 'not submitted'}</small></div><label>Homework<textarea rows="2" value={item.content} onChange={e => editStudent(index, 'content', e.target.value)} /></label><label>Attachment URL<input value={item.attachment_url} onChange={e => editStudent(index, 'attachment_url', e.target.value)} /></label><button onClick={() => submitHomework(item)} disabled={busy || selected.status === 'draft'}><Save />Save submission</button>{item.submission_id && <><label>Score / {selected.max_score}<input type="number" min="0" max={selected.max_score} step="0.01" value={item.score} onChange={e => editStudent(index, 'score', e.target.value)} /></label><label>Feedback<input value={item.feedback} onChange={e => editStudent(index, 'feedback', e.target.value)} /></label><button onClick={() => grade(item)} disabled={busy || item.score === ''}><ClipboardCheck />Grade</button></>}</article>)}</div>{students.length === 0 && <div className="empty-state"><ClipboardCheck /><h3>No students found</h3><p>The assignment class has no active students.</p></div>}</section>}
  </div>
}
