import { Award, BookOpenCheck, Plus, Save, Send } from 'lucide-react'
import { useEffect, useState } from 'react'
import { schoolApi } from '../lib/api'
import { confirmPopup } from '../lib/confirmPopup'

const today = new Date().toISOString().slice(0, 10)
const emptyExam = { name: '', class_id: '', academic_year: `${new Date().getFullYear()}-${new Date().getFullYear() + 1}`, term: '', start_date: today, end_date: today }

export default function ExamManagement({ user }) {
  const [exams, setExams] = useState([]), [classes, setClasses] = useState([]), [subjects, setSubjects] = useState([])
  const [examId, setExamId] = useState(''), [subjectId, setSubjectId] = useState(''), [students, setStudents] = useState([]), [cards, setCards] = useState([])
  const [form, setForm] = useState(emptyExam), [busy, setBusy] = useState(false), [error, setError] = useState(''), [message, setMessage] = useState('')
  const isAdmin = user.role === 'School Admin', selectedExam = exams.find(item => item.id === Number(examId))
  async function load() { setBusy(true); setError(''); try { const [a, b, c] = await Promise.all([schoolApi.exams(), schoolApi.classes(), schoolApi.subjects()]); setExams(a.data || []); setClasses((b.data || []).filter(x => x.status === 'active')); setSubjects((c.data || []).filter(x => x.status === 'active')) } catch (e) { setError(e.message) } finally { setBusy(false) } }
  useEffect(() => { const timer = setTimeout(load, 0); return () => clearTimeout(timer) }, []) // eslint-disable-line react-hooks/exhaustive-deps
  const field = (name, value) => setForm(current => ({ ...current, [name]: value }))
  async function createExam(event) { event.preventDefault(); setBusy(true); setError(''); setMessage(''); try { const result = await schoolApi.createExam({ ...form, class_id: Number(form.class_id) }); setMessage(result.message); setForm(emptyExam); await load(); setExamId(String(result.exam.id)) } catch (e) { setError(e.message) } finally { setBusy(false) } }
  async function loadMarks() { if (!examId || !subjectId) return; setBusy(true); setError(''); setCards([]); try { const result = await schoolApi.examStudents(examId, subjectId); setStudents((result.data || []).map(x => ({ ...x, max_marks: x.max_marks ?? 100, marks_obtained: x.marks_obtained ?? '', grade: x.grade || '', remarks: x.remarks || '' }))) } catch (e) { setError(e.message) } finally { setBusy(false) } }
  function mark(index, name, value) { setStudents(current => current.map((item, i) => i === index ? { ...item, [name]: value } : item)) }
  async function saveMarks() { setBusy(true); setError(''); setMessage(''); try { const marks = students.map(({ student_id, max_marks, marks_obtained, grade, remarks }) => ({ student_id, max_marks: Number(max_marks), marks_obtained: marks_obtained === '' ? null : Number(marks_obtained), grade, remarks })); const result = await schoolApi.saveExamMarks(examId, { subject_id: Number(subjectId), marks }); setMessage(result.message); await loadMarks() } catch (e) { setError(e.message) } finally { setBusy(false) } }
  async function publish() { if (!await confirmPopup({ title: `Publish ${selectedExam.name}?`, message: 'Published results become read-only.', confirmLabel: 'Publish results', tone: 'primary' })) return; setBusy(true); setError(''); try { const result = await schoolApi.publishExam(examId); setMessage(result.message); await load() } catch (e) { setError(e.message) } finally { setBusy(false) } }
  async function report() { if (!examId) return; setBusy(true); setError(''); try { const result = await schoolApi.examReportCards(examId); setCards(result.data || []) } catch (e) { setError(e.message) } finally { setBusy(false) } }
  return <div className="exam-management">
    {isAdmin && <form className="editor-card exam-form" onSubmit={createExam}><div className="editor-heading"><Plus /><div><h3>Create an exam</h3><p>Set the class, academic year and result period.</p></div></div><div className="field-grid three"><label>Exam name *<input required value={form.name} onChange={e => field('name', e.target.value)} /></label><label>Class *<select required value={form.class_id} onChange={e => field('class_id', e.target.value)}><option value="">Select class</option>{classes.map(x => <option key={x.id} value={x.id}>{x.class_name} {x.section || ''}</option>)}</select></label><label>Academic year *<input required value={form.academic_year} onChange={e => field('academic_year', e.target.value)} /></label><label>Term<input value={form.term} onChange={e => field('term', e.target.value)} placeholder="Term 1" /></label><label>Start date *<input required type="date" value={form.start_date} onChange={e => field('start_date', e.target.value)} /></label><label>End date *<input required type="date" value={form.end_date} onChange={e => field('end_date', e.target.value)} /></label></div><button className="button button-small" disabled={busy}><Plus />Create exam</button></form>}
    {error && <div className="form-error exam-message">{error}</div>}{message && <div className="success-notice exam-message">{message}</div>}
    <section className="data-panel"><div className="panel-title"><div><span>Academic results</span><h2>Marks and report cards</h2></div><b>{exams.length} exams</b></div><div className="exam-selector"><label>Exam<select value={examId} onChange={e => { setExamId(e.target.value); setStudents([]); setCards([]) }}><option value="">Select exam</option>{exams.map(x => <option key={x.id} value={x.id}>{x.name} - {x.class_name} ({x.status})</option>)}</select></label><label>Subject<select value={subjectId} onChange={e => { setSubjectId(e.target.value); setStudents([]) }}><option value="">Select subject</option>{subjects.map(x => <option key={x.id} value={x.id}>{x.code} - {x.name}</option>)}</select></label><button className="button button-small" onClick={loadMarks} disabled={busy || !examId || !subjectId}><BookOpenCheck />Load marks</button><button className="refresh-button" onClick={report} disabled={busy || !examId}><Award />Report cards</button>{isAdmin && selectedExam?.status === 'draft' && <button className="refresh-button" onClick={publish} disabled={busy}><Send />Publish</button>}</div>
      {students.length > 0 && <><div className="table-wrap exam-marks"><table><thead><tr><th>Student</th><th>Maximum</th><th>Obtained</th><th>Grade</th><th>Remarks</th></tr></thead><tbody>{students.map((x, i) => <tr key={x.student_id}><td><b>{x.student_name}</b><small>{x.admission_no}</small></td><td><input type="number" min="1" step="0.01" value={x.max_marks} disabled={selectedExam?.status !== 'draft'} onChange={e => mark(i, 'max_marks', e.target.value)} /></td><td><input type="number" min="0" max={x.max_marks} step="0.01" value={x.marks_obtained} disabled={selectedExam?.status !== 'draft'} onChange={e => mark(i, 'marks_obtained', e.target.value)} /></td><td><input maxLength="10" value={x.grade} disabled={selectedExam?.status !== 'draft'} onChange={e => mark(i, 'grade', e.target.value)} /></td><td><input value={x.remarks} disabled={selectedExam?.status !== 'draft'} onChange={e => mark(i, 'remarks', e.target.value)} /></td></tr>)}</tbody></table></div>{selectedExam?.status === 'draft' && <button className="button button-small exam-save" onClick={saveMarks} disabled={busy}><Save />Save marks</button>}</>}
      {cards.length > 0 && <div className="report-card-grid">{cards.map(card => <article key={card.student_id}><div><Award /><span><b>{card.student_name}</b><small>{card.admission_no}</small></span><strong>{card.percentage}%</strong></div><p>{card.total_obtained} / {card.total_max_marks} marks</p><ul>{card.subjects.map(subject => <li key={subject.subject_id}><span>{subject.subject_name}</span><b>{subject.marks_obtained ?? '-'} / {subject.max_marks}</b><em>{subject.grade || '-'}</em></li>)}</ul></article>)}</div>}
      {!busy && exams.length === 0 && <div className="empty-state"><Award /><h3>No exams found</h3><p>Create the first exam to start entering marks.</p></div>}
    </section>
  </div>
}
