import { BellRing, CircleDollarSign, Plus, Receipt, Save } from 'lucide-react'
import { useEffect, useState } from 'react'
import { schoolApi } from '../lib/api'
import { confirmPopup } from '../lib/confirmPopup'

const today = new Date().toISOString().slice(0, 10)
const empty = { name: '', class_id: '', academic_year: `${new Date().getFullYear()}-${new Date().getFullYear() + 1}`, amount: '', due_date: today, description: '' }

export default function FeeManagement() {
  const [structures, setStructures] = useState([]), [invoices, setInvoices] = useState([]), [classes, setClasses] = useState([]), [summary, setSummary] = useState({})
  const [form, setForm] = useState(empty), [status, setStatus] = useState('all'), [payment, setPayment] = useState(null)
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [message, setMessage] = useState('')
  async function load(selected = status) { setBusy(true); setError(''); try { const [a, b, c, d] = await Promise.all([schoolApi.feeStructures(), schoolApi.feeInvoices(selected), schoolApi.feeSummary(), schoolApi.classes()]); setStructures(a.data || []); setInvoices(b.data || []); setSummary(c.summary || {}); setClasses((d.data || []).filter(x => x.status === 'active')) } catch (e) { setError(e.message) } finally { setBusy(false) } }
  useEffect(() => { const timer = setTimeout(() => load('all'), 0); return () => clearTimeout(timer) }, []) // eslint-disable-line react-hooks/exhaustive-deps
  const field = (name, value) => setForm(current => ({ ...current, [name]: value }))
  async function create(event) { event.preventDefault(); setBusy(true); setError(''); try { const result = await schoolApi.createFeeStructure({ ...form, class_id: Number(form.class_id), amount: Number(form.amount) }); setMessage(result.message); setForm(empty); await load() } catch (e) { setError(e.message) } finally { setBusy(false) } }
  async function generate(item) { if (!await confirmPopup({ title: `Generate ${item.name} invoices?`, message: 'One invoice will be created for every active student in this class.', confirmLabel: 'Generate invoices', tone: 'primary' })) return; setBusy(true); try { const result = await schoolApi.generateFeeInvoices(item.id); setMessage(result.message); await load() } catch (e) { setError(e.message) } finally { setBusy(false) } }
  async function pay(event) { event.preventDefault(); setBusy(true); setError(''); try { const result = await schoolApi.recordFeePayment(payment.id, { amount: Number(payment.payment_amount), payment_date: payment.payment_date, payment_method: payment.payment_method, reference_number: payment.reference_number }); setMessage(result.message); setPayment(null); await load() } catch (e) { setError(e.message) } finally { setBusy(false) } }
  async function remind(item) { if (!await confirmPopup({ title: `Queue reminder for ${item.student_name}?`, message: `Outstanding balance: ${item.balance}`, confirmLabel: 'Queue reminder', tone: 'primary' })) return; setBusy(true); try { const result = await schoolApi.queueFeeReminder(item.id, {}); setMessage(result.message) } catch (e) { setError(e.message) } finally { setBusy(false) } }
  return <div className="fee-management">
    <div className="stat-grid compact">{[['Billed', summary.total_billed || 0], ['Collected', summary.total_collected || 0], ['Outstanding', summary.total_outstanding || 0], ['Overdue', summary.overdue_count || 0]].map(([label, value]) => <article key={label}><small>{label}</small><b>{label === 'Overdue' ? value : Number(value).toLocaleString()}</b><span>{label === 'Overdue' ? 'invoices' : 'total amount'}</span></article>)}</div>
    <form className="editor-card" onSubmit={create}><div className="editor-heading"><CircleDollarSign /><div><h3>Create fee structure</h3><p>Define the fee, class, amount and payment deadline.</p></div></div><div className="field-grid three"><label>Fee name *<input required value={form.name} onChange={e => field('name', e.target.value)} /></label><label>Class *<select required value={form.class_id} onChange={e => field('class_id', e.target.value)}><option value="">Select class</option>{classes.map(x => <option key={x.id} value={x.id}>{x.class_name}</option>)}</select></label><label>Academic year *<input required value={form.academic_year} onChange={e => field('academic_year', e.target.value)} /></label><label>Amount *<input required type="number" min="0.01" step="0.01" value={form.amount} onChange={e => field('amount', e.target.value)} /></label><label>Due date *<input required type="date" value={form.due_date} onChange={e => field('due_date', e.target.value)} /></label><label>Description<input value={form.description} onChange={e => field('description', e.target.value)} /></label></div><button className="button button-small" disabled={busy}><Plus />Create fee</button></form>
    {error && <div className="form-error">{error}</div>}{message && <div className="success-notice">{message}</div>}
    <section className="data-panel"><div className="panel-title"><div><span>Fee setup</span><h2>Fee structures</h2></div><b>{structures.length} fees</b></div><div className="fee-structure-list">{structures.map(item => <article key={item.id}><div><b>{item.name}</b><small>{item.class_name} / {item.academic_year} / due {item.due_date}</small></div><strong>{item.amount.toLocaleString()}</strong><button className="refresh-button" onClick={() => generate(item)} disabled={busy}><Receipt />Generate invoices</button></article>)}</div></section>
    <section className="data-panel"><div className="panel-title"><div><span>Collection register</span><h2>Student invoices</h2></div><select value={status} onChange={e => { setStatus(e.target.value); load(e.target.value) }}>{['all','pending','partial','paid','overdue'].map(x => <option key={x}>{x}</option>)}</select></div><div className="table-wrap fee-table"><table><thead><tr><th>Student</th><th>Fee</th><th>Due</th><th>Paid / Balance</th><th>Status</th><th>Actions</th></tr></thead><tbody>{invoices.map(item => <tr key={item.id}><td><b>{item.student_name}</b><small>{item.admission_no}</small></td><td>{item.fee_name}<small>{item.class_name}</small></td><td>{item.due_date}</td><td>{item.paid_amount} / {item.balance}</td><td><span className={`delivery-status ${item.status}`}>{item.status}</span></td><td><div className="student-row-actions">{!['paid','cancelled'].includes(item.status) && <button onClick={() => setPayment({ ...item, payment_amount: item.balance, payment_date: today, payment_method: 'cash', reference_number: '' })}><Save />Payment</button>}{!['paid','cancelled'].includes(item.status) && <button onClick={() => remind(item)}><BellRing />Reminder</button>}</div></td></tr>)}</tbody></table></div>{invoices.length === 0 && <div className="empty-state"><Receipt /><h3>No invoices found</h3><p>Generate invoices from a fee structure.</p></div>}</section>
    {payment && <form className="editor-card" onSubmit={pay}><div className="editor-heading"><Save /><div><h3>Record payment</h3><p>{payment.student_name} / balance {payment.balance}</p></div></div><div className="field-grid three"><label>Amount *<input required type="number" min="0.01" max={payment.balance} step="0.01" value={payment.payment_amount} onChange={e => setPayment({ ...payment, payment_amount: e.target.value })} /></label><label>Payment date *<input required type="date" value={payment.payment_date} onChange={e => setPayment({ ...payment, payment_date: e.target.value })} /></label><label>Method<select value={payment.payment_method} onChange={e => setPayment({ ...payment, payment_method: e.target.value })}>{['cash','card','bank_transfer','upi','cheque','online'].map(x => <option key={x}>{x}</option>)}</select></label><label>Reference<input value={payment.reference_number} onChange={e => setPayment({ ...payment, reference_number: e.target.value })} /></label></div><div className="student-row-actions"><button className="button button-small" disabled={busy}><Save />Save payment</button><button type="button" onClick={() => setPayment(null)}>Cancel</button></div></form>}
  </div>
}
