import { BookOpen, Library, Plus, RotateCcw } from 'lucide-react'
import { useEffect, useState } from 'react'
import { schoolApi } from '../lib/api'
import { confirmPopup } from '../lib/confirmPopup'

const today = new Date().toISOString().slice(0, 10)
const due = new Date(Date.now() + 14 * 86400000).toISOString().slice(0, 10)
const empty = { isbn: '', title: '', author: '', publisher: '', category: '', shelf_location: '', total_copies: 1 }

export default function LibraryManagement() {
  const [books, setBooks] = useState([]), [loans, setLoans] = useState([]), [students, setStudents] = useState([]), [summary, setSummary] = useState({})
  const [form, setForm] = useState(empty), [issue, setIssue] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState(''), [message, setMessage] = useState('')
  async function load() { setBusy(true); setError(''); try { const [a, b, c, d] = await Promise.all([schoolApi.libraryBooks(), schoolApi.libraryLoans(), schoolApi.librarySummary(), schoolApi.students()]); setBooks(a.data || []); setLoans(b.data || []); setSummary(c.summary || {}); setStudents((d.data || []).filter(x => x.status === 'active')) } catch (e) { setError(e.message) } finally { setBusy(false) } }
  useEffect(() => { const timer = setTimeout(load, 0); return () => clearTimeout(timer) }, [])
  const field = (name, value) => setForm(current => ({ ...current, [name]: value }))
  async function create(event) { event.preventDefault(); setBusy(true); setError(''); try { const result = await schoolApi.createLibraryBook({ ...form, total_copies: Number(form.total_copies) }); setMessage(result.message); setForm(empty); await load() } catch (e) { setError(e.message) } finally { setBusy(false) } }
  async function issueBook(event) { event.preventDefault(); setBusy(true); setError(''); try { const result = await schoolApi.issueLibraryBook(issue.id, { student_id: Number(issue.student_id), issued_at: issue.issued_at, due_date: issue.due_date, notes: issue.notes }); setMessage(result.message); setIssue(null); await load() } catch (e) { setError(e.message) } finally { setBusy(false) } }
  async function returnBook(item) { if (!await confirmPopup({ title: `Return ${item.title}?`, message: `Return this book from ${item.student_name}.`, confirmLabel: 'Return book', tone: 'primary' })) return; setBusy(true); try { const result = await schoolApi.returnLibraryBook(item.id, { returned_at: today, fine_amount: 0 }); setMessage(result.message); await load() } catch (e) { setError(e.message) } finally { setBusy(false) } }
  return <div className="library-management">
    <div className="stat-grid compact">{[['Book titles',summary.book_titles||0],['Total copies',summary.total_copies||0],['Active loans',summary.active_loans||0],['Overdue',summary.overdue_loans||0]].map(([a,b])=><article key={a}><small>{a}</small><b>{b}</b><span>library</span></article>)}</div>
    <form className="editor-card" onSubmit={create}><div className="editor-heading"><Plus/><div><h3>Add library book</h3><p>Create a searchable book inventory record.</p></div></div><div className="field-grid three"><label>ISBN<input value={form.isbn} onChange={e=>field('isbn',e.target.value)}/></label><label>Title *<input required value={form.title} onChange={e=>field('title',e.target.value)}/></label><label>Author *<input required value={form.author} onChange={e=>field('author',e.target.value)}/></label><label>Publisher<input value={form.publisher} onChange={e=>field('publisher',e.target.value)}/></label><label>Category<input value={form.category} onChange={e=>field('category',e.target.value)}/></label><label>Shelf<input value={form.shelf_location} onChange={e=>field('shelf_location',e.target.value)}/></label><label>Total copies *<input required type="number" min="1" value={form.total_copies} onChange={e=>field('total_copies',e.target.value)}/></label></div><button className="button button-small" disabled={busy}><Plus/>Add book</button></form>
    {error&&<div className="form-error">{error}</div>}{message&&<div className="success-notice">{message}</div>}
    <section className="data-panel"><div className="panel-title"><div><span>Book catalogue</span><h2>Library inventory</h2></div><b>{books.length} titles</b></div><div className="library-book-grid">{books.map(item=><article key={item.id}><Library/><div><b>{item.title}</b><small>{item.author} / {item.category||'General'} / shelf {item.shelf_location||'-'}</small><p>{item.available_copies} of {item.total_copies} available</p></div><button disabled={!item.available_copies} onClick={()=>setIssue({...item,student_id:'',issued_at:today,due_date:due,notes:''})}><BookOpen/>Issue</button></article>)}</div>{books.length===0&&<div className="empty-state"><Library/><h3>No books found</h3><p>Add your first library book.</p></div>}</section>
    <section className="data-panel"><div className="panel-title"><div><span>Circulation</span><h2>Book loans</h2></div><b>{loans.length} records</b></div><div className="table-wrap library-loans"><table><thead><tr><th>Student</th><th>Book</th><th>Issued</th><th>Due</th><th>Status</th><th>Action</th></tr></thead><tbody>{loans.map(item=><tr key={item.id}><td><b>{item.student_name}</b><small>{item.admission_no}</small></td><td>{item.title}<small>{item.isbn||'No ISBN'}</small></td><td>{item.issued_at}</td><td>{item.due_date}</td><td><span className={`delivery-status ${item.status}`}>{item.status}</span></td><td>{['issued','overdue'].includes(item.status)&&<button className="refresh-button" onClick={()=>returnBook(item)}><RotateCcw/>Return</button>}</td></tr>)}</tbody></table></div></section>
    {issue&&<form className="editor-card" onSubmit={issueBook}><div className="editor-heading"><BookOpen/><div><h3>Issue {issue.title}</h3><p>Select a student and return deadline.</p></div></div><div className="field-grid three"><label>Student *<select required value={issue.student_id} onChange={e=>setIssue({...issue,student_id:e.target.value})}><option value="">Select student</option>{students.map(x=><option key={x.id} value={x.id}>{x.first_name} {x.last_name||''} / {x.admission_no}</option>)}</select></label><label>Issue date *<input required type="date" value={issue.issued_at} onChange={e=>setIssue({...issue,issued_at:e.target.value})}/></label><label>Due date *<input required type="date" value={issue.due_date} onChange={e=>setIssue({...issue,due_date:e.target.value})}/></label><label>Notes<input value={issue.notes} onChange={e=>setIssue({...issue,notes:e.target.value})}/></label></div><div className="student-row-actions"><button className="button button-small" disabled={busy}><BookOpen/>Issue book</button><button type="button" onClick={()=>setIssue(null)}>Cancel</button></div></form>}
  </div>
}
