import { Link2, Unlink } from 'lucide-react'
import { useEffect, useState } from 'react'
import { schoolApi } from '../lib/api'
import { confirmPopup } from '../lib/confirmPopup'

export default function ParentRelationshipManager({ parent, canManage }) {
  const [children,setChildren]=useState([]), [students,setStudents]=useState([])
  const [form,setForm]=useState({student_id:'',relationship_type:'guardian',is_primary:false})
  const [busy,setBusy]=useState(false), [error,setError]=useState(''), [message,setMessage]=useState('')
  async function load(){const result=await schoolApi.parentStudents(parent.id);setChildren(result.data||[])}
  useEffect(()=>{const timer=setTimeout(()=>{schoolApi.parentStudents(parent.id).then(r=>setChildren(r.data||[])).catch(e=>setError(e.message));if(canManage)schoolApi.students().then(r=>setStudents((r.data||r.students||[]).filter(x=>x.status==='active'))).catch(e=>setError(e.message))},0);return()=>clearTimeout(timer)},[parent.id,canManage])
  async function link(event){event.preventDefault();setBusy(true);setError('');setMessage('');try{const result=await schoolApi.linkParentStudent(parent.id,{...form,student_id:Number(form.student_id)});setMessage(result.message);setForm({student_id:'',relationship_type:'guardian',is_primary:false});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function unlink(child){if(!await confirmPopup({title:`Unlink ${child.first_name} ${child.last_name||''}?`,message:'Relationship history will be preserved.',confirmLabel:'Unlink student'}))return;setBusy(true);setError('');try{const result=await schoolApi.unlinkParentStudent(parent.id,child.student_id);setMessage(result.message);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  return <div className="relationship-section"><div className="relationship-heading"><div><span>Linked students</span><h3>Children and dependants</h3></div><b>{children.filter(x=>x.status==='active').length} active</b></div>{error&&<div className="form-error">{error}</div>}{message&&<div className="success-notice">{message}</div>}{canManage&&parent.status==='active'&&<form className="relationship-form" onSubmit={link}><label>Student<select required value={form.student_id} onChange={e=>setForm({...form,student_id:e.target.value})}><option value="">Select active student</option>{students.map(x=><option key={x.id} value={x.id}>{x.first_name} {x.last_name||''} · {x.admission_no}</option>)}</select></label><label>Relationship<select value={form.relationship_type} onChange={e=>setForm({...form,relationship_type:e.target.value})}><option value="father">Father</option><option value="mother">Mother</option><option value="guardian">Guardian</option><option value="other">Other</option></select></label><label className="primary-check"><input type="checkbox" checked={form.is_primary} onChange={e=>setForm({...form,is_primary:e.target.checked})}/>Primary contact</label><button className="button button-small" disabled={busy}><Link2/>Link student</button></form>}{children.length===0?<div className="relationship-empty">No students linked to this parent.</div>:<div className="relationship-list">{children.map(child=><article key={child.relationship_id} className={child.status}><div><b>{child.first_name} {child.last_name||''}</b><small>{child.admission_no} · {child.class_name||'No class'} {child.section||''}</small></div><span>{child.relationship_type}{child.is_primary?' · Primary':''}</span>{canManage&&child.status==='active'&&<button onClick={()=>unlink(child)} disabled={busy}><Unlink/>Unlink</button>}</article>)}</div>}</div>
}
