/* eslint-disable react-hooks/set-state-in-effect */
import { Link2, Trash2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import { schoolApi } from '../lib/api'
import { confirmPopup } from '../lib/confirmPopup'

export default function PortalLinkManager() {
  const [type, setType] = useState('parent'), [options, setOptions] = useState({users:[],profiles:[]}), [links, setLinks] = useState([])
  const [values, setValues] = useState({user_id:'',profile_id:''}), [error, setError] = useState(''), [notice, setNotice] = useState('')
  const load = async () => { try { const [available, current] = await Promise.all([schoolApi.portalLinkOptions(type), schoolApi.portalLinks()]); setOptions(available); setLinks(current.data || []); setValues({user_id:'',profile_id:''}) } catch (e) { setError(e.message) } }
  useEffect(() => { load() }, [type])
  async function submit(e) { e.preventDefault(); setError(''); try { const result = await schoolApi.createPortalLink({...values, profile_type:type}); setNotice(result.message); await load() } catch (err) { setError(err.message) } }
  async function revoke(id) { if (!await confirmPopup({title:'Revoke portal link?',message:'The linked account will immediately lose access to this profile.',confirmLabel:'Revoke link'})) return; try { const result=await schoolApi.revokePortalLink(id); setNotice(result.message); await load() } catch (err) { setError(err.message) } }
  return <><section className="people-hero"><div><span>School Admin</span><h2>Portal access links</h2><p>Connect a Parent or Student login to its matching school profile.</p></div><Link2/></section><form className="editor-card" onSubmit={submit}><div className="field-grid three"><label>Account type<select value={type} onChange={e=>setType(e.target.value)}><option value="parent">Parent</option><option value="student">Student</option></select></label><label>Login account<select required value={values.user_id} onChange={e=>setValues({...values,user_id:e.target.value})}><option value="">Select {type} account</option>{options.users.map(user=><option key={user.id} value={user.id}>{user.name} · {user.email}</option>)}</select></label><label>School profile<select required value={values.profile_id} onChange={e=>setValues({...values,profile_id:e.target.value})}><option value="">Select {type} profile</option>{options.profiles.map(profile=><option key={profile.id} value={profile.id}>{profile.name}{profile.admission_no?` · ${profile.admission_no}`:` · ${profile.mobile}`}</option>)}</select></label></div>{error&&<div className="form-error">{error}</div>}{notice&&<div className="success-notice">{notice}</div>}<button className="button button-small"><Link2 size={16}/>Link account</button></form><section className="data-panel"><div className="panel-title"><div><span>Access history</span><h2>Profile links</h2></div><b>{links.length} records</b></div><div className="table-wrap"><table><thead><tr><th>Account</th><th>Profile type</th><th>Profile ID</th><th>Status</th><th>Linked</th><th>Action</th></tr></thead><tbody>{links.map(link=><tr key={link.id}><td><b>{link.user_name}</b><small>{link.user_email}</small></td><td>{link.profile_type}</td><td>{link.profile_id}</td><td>{link.status}</td><td>{new Date(link.linked_at).toLocaleDateString()}</td><td>{link.status==='active'&&<button className="danger" onClick={()=>revoke(link.id)}><Trash2 size={15}/>Revoke</button>}</td></tr>)}</tbody></table></div></section></>
}
