/* eslint-disable react-hooks/set-state-in-effect */
import { CalendarDays, MapPin, Plus, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { schoolApi } from '../lib/api'
import { confirmPopup } from '../lib/confirmPopup'

const types = ['event','holiday','exam','meeting','activity']
const audiences = ['all','staff','parent','student']
const toInput = value => value ? new Date(value).toISOString().slice(0,16) : ''
const localDate = value => value ? new Date(value).toLocaleString([], {dateStyle:'medium',timeStyle:'short'}) : '—'

export default function SchoolCalendar({ user }) {
  const [events,setEvents] = useState([]), [open,setOpen] = useState(false), [editing,setEditing] = useState(null)
  const [busy,setBusy] = useState(false), [error,setError] = useState(''), [notice,setNotice] = useState('')
  const load = async () => { setBusy(true); setError(''); try { const result=await schoolApi.calendarEvents(); setEvents(result.data || []) } catch(e) { setError(e.message) } finally { setBusy(false) } }
  useEffect(() => { load() }, [])
  const canManage = user.role === 'School Admin'
  async function cancel(event) { if (!await confirmPopup({title:'Cancel this event?',message:'Families and staff will no longer see this event.',confirmLabel:'Cancel event'})) return; try { const result=await schoolApi.cancelCalendarEvent(event.id); setNotice(result.message); load() } catch(e) { setError(e.message) } }
  return <><section className="people-hero"><div><span>School calendar</span><h2>Events, holidays and meetings</h2><p>Share important dates with the right school audience.</p></div><CalendarDays/></section>{canManage&&<div className="page-actions"><p>Create and publish calendar events for staff, parents and students.</p><button className="button button-small" onClick={()=>{setEditing(null);setOpen(!open)}}><Plus size={16}/>{open?'Close form':'Add event'}</button></div>}{open&&<EventForm initial={editing} onDone={message=>{setNotice(message);setOpen(false);load()}} onClose={()=>setOpen(false)}/>} {error&&<div className="form-error">{error}</div>}{notice&&<div className="success-notice">{notice}</div>}{busy?<div className="loading-grid"><i/><i/><i/></div>:<section className="calendar-event-grid">{events.length?events.map(event=><article key={event.id} className={`calendar-event ${event.status}`}><div className="calendar-event-date"><b>{new Date(event.starts_at).getDate()}</b><small>{new Date(event.starts_at).toLocaleString('default',{month:'short'})}</small></div><div><span>{event.event_type} · {event.audience}</span><h3>{event.title}</h3><p>{event.description || 'No additional details.'}</p><small>{localDate(event.starts_at)} — {localDate(event.ends_at)}</small>{event.location&&<small><MapPin size={13}/>{event.location}</small>}</div>{canManage&&event.status!=='cancelled'&&<div className="calendar-actions"><button onClick={()=>{setEditing(event);setOpen(true)}}>Edit</button><button className="danger" onClick={()=>cancel(event)}>Cancel</button></div>}</article>):<div className="empty-state"><CalendarDays/><h3>No calendar events</h3><p>Add a school event, holiday, meeting, exam or activity.</p></div>}</section>}</>
}

function EventForm({ initial, onDone, onClose }) {
  const base={title:'',description:'',event_type:'event',starts_at:'',ends_at:'',all_day:false,location:'',audience:'all',status:'draft'}
  const [values,setValues]=useState(initial?{...initial,starts_at:toInput(initial.starts_at),ends_at:toInput(initial.ends_at)}:base), [busy,setBusy]=useState(false), [error,setError]=useState('')
  const field=(key,value)=>setValues({...values,[key]:value})
  async function submit(e) { e.preventDefault(); setBusy(true); setError(''); try { const result=initial?await schoolApi.updateCalendarEvent(initial.id,values):await schoolApi.createCalendarEvent(values); onDone(result.message) } catch(err) { setError(err.message) } finally { setBusy(false) } }
  return <form className="editor-card" onSubmit={submit}><div className="editor-heading"><CalendarDays/><div><h3>{initial?'Edit event':'Create event'}</h3><p>Only published events are visible to the selected audience.</p></div><button type="button" className="refresh-button" onClick={onClose}><X size={16}/>Close</button></div><div className="field-grid three"><label>Title *<input required maxLength="180" value={values.title} onChange={e=>field('title',e.target.value)}/></label><label>Type<select value={values.event_type} onChange={e=>field('event_type',e.target.value)}>{types.map(type=><option key={type}>{type}</option>)}</select></label><label>Audience<select value={values.audience} onChange={e=>field('audience',e.target.value)}>{audiences.map(audience=><option key={audience}>{audience}</option>)}</select></label><label>Starts *<input required type="datetime-local" value={values.starts_at} onChange={e=>field('starts_at',e.target.value)}/></label><label>Ends *<input required type="datetime-local" value={values.ends_at} onChange={e=>field('ends_at',e.target.value)}/></label><label>Status<select value={values.status} onChange={e=>field('status',e.target.value)}><option value="draft">draft</option><option value="published">published</option></select></label><label>Location<input value={values.location || ''} onChange={e=>field('location',e.target.value)}/></label><label className="calendar-checkbox"><input type="checkbox" checked={values.all_day} onChange={e=>field('all_day',e.target.checked)}/>All-day event</label><label className="wide">Description<textarea rows="3" value={values.description || ''} onChange={e=>field('description',e.target.value)}/></label></div>{error&&<div className="form-error">{error}</div>}<button className="button button-small" disabled={busy}>{busy?'Saving…':initial?'Save event':'Create event'}</button></form>
}
