/* eslint-disable react-hooks/set-state-in-effect */
import { Award, BriefcaseBusiness, FileText, Save, Star, UsersRound } from 'lucide-react'
import { useEffect, useState } from 'react'
import { schoolApi } from '../lib/api'

const today = new Date().toISOString().slice(0, 10)
const emptyDocument = { teacher_id: '', document_type: 'Identity', title: '', document_url: '', issued_on: '', expires_on: '', notes: '' }
const emptyContract = { teacher_id: '', contract_type: 'Full-time', start_date: today, end_date: '', document_url: '', notes: '' }
const emptyReview = { teacher_id: '', review_period: '', review_date: today, rating: '4', goals: '', feedback: '' }

export default function StaffHRManagement({ user }) {
  const admin = user.role === 'School Admin'
  const [staff, setStaff] = useState([]), [documents, setDocuments] = useState([]), [contracts, setContracts] = useState([]), [reviews, setReviews] = useState([]), [salaryHistory, setSalaryHistory] = useState([])
  const [selected, setSelected] = useState(''), [tab, setTab] = useState('overview'), [busy, setBusy] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('')
  const [document, setDocument] = useState(emptyDocument), [contract, setContract] = useState(emptyContract), [review, setReview] = useState(emptyReview)

  async function load(teacherId = selected) {
    setBusy(true); setError('')
    try { const [summary, docs, contractsResult, reviewsResult, history] = await Promise.all([schoolApi.hrStaff(teacherId), schoolApi.hrDocuments(teacherId), schoolApi.hrContracts(teacherId), schoolApi.hrReviews(teacherId), schoolApi.hrSalaryHistory(teacherId)]); setStaff(summary.data || []); setDocuments(docs.data || []); setContracts(contractsResult.data || []); setReviews(reviewsResult.data || []); setSalaryHistory(history.data || []) }
    catch (err) { setError(err.message) } finally { setBusy(false) }
  }
  // Initial HR directory load intentionally uses the empty staff selection.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { load() }, [])
  const selectedStaff = staff.find(item => String(item.teacher_id) === String(selected))
  const choose = value => { setSelected(value); setTab('overview'); load(value) }
  const save = async (action, values, reset) => { setSaving(true); setError(''); setNotice(''); try { const result = await action(values); setNotice(result.message); reset(); await load() } catch (err) { setError(err.message) } finally { setSaving(false) } }
  const field = (setter, name, value) => setter(current => ({ ...current, [name]: value }))
  const teacherOptions = <label>Staff member<select required value={document.teacher_id || contract.teacher_id || review.teacher_id || selected} onChange={event => { const value = event.target.value; setDocument(current => ({ ...current, teacher_id: value })); setContract(current => ({ ...current, teacher_id: value })); setReview(current => ({ ...current, teacher_id: value })); setSelected(value) }}><option value="">Select staff member</option>{staff.map(item => <option key={item.teacher_id} value={item.teacher_id}>{item.full_name}</option>)}</select></label>
  return <div className="staff-hr-management"><section className="people-hero"><div><span>People operations</span><h2>Staff HR and leave records</h2><p>Manage staff profiles, contracts, documents, performance reviews, salary history, attendance, and leave approvals.</p></div><UsersRound/></section>{error && <div className="form-error" role="alert">{error}</div>}{notice && <div className="success-notice" role="status">{notice}</div>}<div className="page-actions"><label>View staff<select value={selected} onChange={event => choose(event.target.value)}><option value="">All active staff</option>{staff.map(item => <option key={item.teacher_id} value={item.teacher_id}>{item.full_name}</option>)}</select></label><button className="button button-small" onClick={() => load()} disabled={busy}>Refresh</button></div>{selectedStaff && <section className="data-panel hr-profile-card"><div><span>Staff profile</span><h2>{selectedStaff.full_name}</h2><p>{selectedStaff.designation || 'Teacher'} · {selectedStaff.department || 'School team'} · Joined {selectedStaff.joining_date || '—'}</p></div><div><b>{selectedStaff.present_days + selectedStaff.absent_days + selectedStaff.leave_days}</b><small>attendance records</small></div><div><b>{selectedStaff.average_rating || '—'}</b><small>average review rating</small></div></section>}<div className="hr-tabs">{[['overview','Overview'],['documents','Documents'],['contracts','Contracts'],['reviews','Performance reviews'],['salary','Salary history']].map(([key,label]) => <button key={key} className={tab === key ? 'active' : ''} onClick={() => setTab(key)}>{label}</button>)}</div>{busy ? <div className="loading-grid"><i/><i/><i/></div> : tab === 'overview' ? <OverviewRows rows={staff} onSelect={choose}/> : tab === 'documents' ? <Documents rows={documents} admin={admin} teacherOptions={teacherOptions} value={document} setValue={setDocument} saving={saving} save={save} field={field}/> : tab === 'contracts' ? <Contracts rows={contracts} admin={admin} teacherOptions={teacherOptions} value={contract} setValue={setContract} saving={saving} save={save} field={field}/> : tab === 'reviews' ? <Reviews rows={reviews} admin={admin} teacherOptions={teacherOptions} value={review} setValue={setReview} saving={saving} save={save} field={field}/> : <SalaryHistory rows={salaryHistory}/>}</div>
}

function OverviewRows({ rows, onSelect }) { return <section className="data-panel"><div className="panel-title"><div><span>Staff directory</span><h2>HR overview</h2></div><b>{rows.length} staff</b></div><div className="table-wrap"><table><thead><tr><th>Staff member</th><th>Department</th><th>Salary</th><th>Attendance</th><th>Documents</th><th>Review</th><th>Action</th></tr></thead><tbody>{rows.map(row => <tr key={row.teacher_id}><td><b>{row.full_name}</b><small>{row.email}</small></td><td>{row.department || '—'}</td><td>{row.basic_salary == null ? 'Not configured' : `₹${Number(row.basic_salary) + Number(row.allowances || 0) - Number(row.deductions || 0)}`}</td><td>{row.present_days} present · {row.absent_days} absent</td><td>{row.document_count}</td><td>{row.average_rating || '—'} / 5</td><td><button className="button button-small button-ghost" onClick={() => onSelect(String(row.teacher_id))}>Open</button></td></tr>)}</tbody></table></div></section> }

function Documents({ rows, admin, teacherOptions, value, setValue, saving, save, field }) { return <><section className="data-panel"><div className="panel-title"><div><span>Staff records</span><h2>Documents</h2></div><b>{rows.length} records</b></div><div className="table-wrap"><table><thead><tr><th>Staff</th><th>Document</th><th>Type</th><th>Issued</th><th>Expires</th><th>Status</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td>{row.full_name}</td><td><b>{row.title}</b><small>{row.document_url || 'No file link'}</small></td><td>{row.document_type}</td><td>{row.issued_on || '—'}</td><td>{row.expires_on || '—'}</td><td>{row.status}</td></tr>)}</tbody></table></div></section>{admin && <form className="editor-card" onSubmit={event => { event.preventDefault(); save(schoolApi.createHrDocument, value, () => setValue(emptyDocument)) }}><div className="editor-heading"><FileText/><div><h3>Add staff document</h3><p>Store a secure document link and expiry date for compliance tracking.</p></div></div><div className="field-grid three">{teacherOptions}<label>Document type<input required value={value.document_type} onChange={event => field(setValue, 'document_type', event.target.value)}/></label><label>Title<input required value={value.title} onChange={event => field(setValue, 'title', event.target.value)}/></label><label>Document URL<input value={value.document_url} onChange={event => field(setValue, 'document_url', event.target.value)}/></label><label>Issued on<input type="date" value={value.issued_on} onChange={event => field(setValue, 'issued_on', event.target.value)}/></label><label>Expires on<input type="date" value={value.expires_on} onChange={event => field(setValue, 'expires_on', event.target.value)}/></label><label className="wide">Notes<textarea value={value.notes} onChange={event => field(setValue, 'notes', event.target.value)}/></label></div><button className="button button-small" disabled={saving}><Save size={16}/>{saving ? 'Saving…' : 'Save document'}</button></form>}</> }

function Contracts({ rows, admin, teacherOptions, value, setValue, saving, save, field }) { return <><section className="data-panel"><div className="panel-title"><div><span>Employment records</span><h2>Contracts</h2></div><b>{rows.length} records</b></div><div className="table-wrap"><table><thead><tr><th>Staff</th><th>Type</th><th>Start</th><th>End</th><th>Status</th><th>Notes</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td>{row.full_name}</td><td>{row.contract_type}</td><td>{row.start_date}</td><td>{row.end_date || 'Open-ended'}</td><td>{row.status}</td><td>{row.notes || '—'}</td></tr>)}</tbody></table></div></section>{admin && <form className="editor-card" onSubmit={event => { event.preventDefault(); save(schoolApi.createHrContract, value, () => setValue(emptyContract)) }}><div className="editor-heading"><BriefcaseBusiness/><div><h3>Add employment contract</h3><p>Track contract dates, type, and supporting document link.</p></div></div><div className="field-grid three">{teacherOptions}<label>Contract type<input required value={value.contract_type} onChange={event => field(setValue, 'contract_type', event.target.value)}/></label><label>Start date<input required type="date" value={value.start_date} onChange={event => field(setValue, 'start_date', event.target.value)}/></label><label>End date<input type="date" value={value.end_date} onChange={event => field(setValue, 'end_date', event.target.value)}/></label><label>Document URL<input value={value.document_url} onChange={event => field(setValue, 'document_url', event.target.value)}/></label><label className="wide">Notes<textarea value={value.notes} onChange={event => field(setValue, 'notes', event.target.value)}/></label></div><button className="button button-small" disabled={saving}><Save size={16}/>{saving ? 'Saving…' : 'Save contract'}</button></form>}</> }

function Reviews({ rows, admin, teacherOptions, value, setValue, saving, save, field }) { return <><section className="data-panel"><div className="panel-title"><div><span>Staff development</span><h2>Performance reviews</h2></div><b>{rows.length} reviews</b></div><div className="table-wrap"><table><thead><tr><th>Staff</th><th>Period</th><th>Date</th><th>Rating</th><th>Goals</th><th>Feedback</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td>{row.full_name}</td><td>{row.review_period}</td><td>{row.review_date}</td><td><span className="rating-badge"><Star size={12}/>{row.rating} / 5</span></td><td>{row.goals || '—'}</td><td>{row.feedback || '—'}</td></tr>)}</tbody></table></div></section>{admin && <form className="editor-card" onSubmit={event => { event.preventDefault(); save(schoolApi.createHrReview, value, () => setValue(emptyReview)) }}><div className="editor-heading"><Award/><div><h3>Publish performance review</h3><p>Record a review score, goals, and actionable feedback.</p></div></div><div className="field-grid three">{teacherOptions}<label>Review period<input required value={value.review_period} onChange={event => field(setValue, 'review_period', event.target.value)} placeholder="2026 Term 1"/></label><label>Review date<input required type="date" value={value.review_date} onChange={event => field(setValue, 'review_date', event.target.value)}/></label><label>Rating<select value={value.rating} onChange={event => field(setValue, 'rating', event.target.value)}>{['1','2','3','4','5'].map(item => <option key={item}>{item}</option>)}</select></label><label className="wide">Goals<textarea value={value.goals} onChange={event => field(setValue, 'goals', event.target.value)}/></label><label className="wide">Feedback<textarea required value={value.feedback} onChange={event => field(setValue, 'feedback', event.target.value)}/></label></div><button className="button button-small" disabled={saving}><Save size={16}/>{saving ? 'Publishing…' : 'Publish review'}</button></form>}</> }

function SalaryHistory({ rows }) { return <section className="data-panel"><div className="panel-title"><div><span>Compensation</span><h2>Salary history</h2></div><b>{rows.length} changes</b></div>{!rows.length ? <div className="empty-state"><BriefcaseBusiness/><h3>No salary history</h3><p>Salary changes saved from Payroll will appear here.</p></div> : <div className="table-wrap"><table><thead><tr><th>Staff</th><th>Effective from</th><th>Effective to</th><th>Basic</th><th>Allowances</th><th>Deductions</th><th>Reason</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td>{row.full_name}</td><td>{row.effective_from}</td><td>{row.effective_to || 'Current'}</td><td>₹{row.basic_salary}</td><td>₹{row.allowances}</td><td>₹{row.deductions}</td><td>{row.change_reason || '—'}</td></tr>)}</tbody></table></div>}</section> }
