import { CalendarDays, Edit3, Plus, Save, Trash2, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { schoolApi } from '../lib/api'
import { confirmPopup } from '../lib/confirmPopup'

const days = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
const blank = { class_id:'', subject_id:'', teacher_id:'', weekday:0, start_time:'08:00', end_time:'09:00', room:'' }

export default function TimetableDirectory({ rows, canManage, reload }) {
  const [options,setOptions]=useState({classes:[],subjects:[],teachers:[]})
  const [editing,setEditing]=useState(null), [form,setForm]=useState(blank)
  const [busy,setBusy]=useState(false), [error,setError]=useState(''), [message,setMessage]=useState('')
  useEffect(()=>{Promise.all([schoolApi.classes(),schoolApi.subjects(),schoolApi.teachers()]).then(([c,s,t])=>setOptions({classes:(c.data||[]).filter(x=>x.status==='active'),subjects:(s.data||[]).filter(x=>x.status==='active'),teachers:(t.data||[]).filter(x=>x.status==='active')})).catch(e=>setError(e.message))},[])
  const field=(name,value)=>setForm({...form,[name]:value})
  function open(row){setEditing(row?.id||'new');setForm(row?{class_id:row.class_id,subject_id:row.subject_id,teacher_id:row.teacher_id,weekday:row.weekday,start_time:row.start_time.slice(0,5),end_time:row.end_time.slice(0,5),room:row.room||''}:blank);setError('');setMessage('')}
  async function save(e){e.preventDefault();setBusy(true);setError('');try{const result=editing==='new'?await schoolApi.createTimetablePeriod(form):await schoolApi.updateTimetablePeriod(editing,form);setMessage(result.message);setEditing(null);await reload()}catch(err){setError(err.message)}finally{setBusy(false)}}
  async function archive(row){if(!await confirmPopup({title:`Archive ${days[row.weekday]} period?`,message:`The ${row.start_time.slice(0,5)} class period will become inactive.`,confirmLabel:'Archive period'}))return;setBusy(true);setError('');try{const result=await schoolApi.deleteTimetablePeriod(row.id);setMessage(result.message);await reload()}catch(err){setError(err.message)}finally{setBusy(false)}}
  return <><div className="page-actions"><p>Build the weekly schedule and prevent class or teacher overlaps.</p>{canManage&&<button className="button button-small" onClick={()=>editing?setEditing(null):open()}>{editing?<X size={17}/>:<Plus size={17}/>} {editing?'Close form':'Add period'}</button>}</div>{message&&<div className="success-notice">{message}</div>}{error&&<div className="form-error timetable-message">{error}</div>}
    {editing&&<form className="editor-card" onSubmit={save}><div className="editor-heading"><CalendarDays/><div><h3>{editing==='new'?'Add timetable period':'Edit timetable period'}</h3><p>All selected records must be active.</p></div></div><div className="field-grid three"><label>Day *<select value={form.weekday} onChange={e=>field('weekday',Number(e.target.value))}>{days.map((d,i)=><option key={d} value={i}>{d}</option>)}</select></label><label>Class *<select required value={form.class_id} onChange={e=>field('class_id',e.target.value)}><option value="">Select class</option>{options.classes.map(x=><option key={x.id} value={x.id}>{x.class_name}{x.section?` - ${x.section}`:''}</option>)}</select></label><label>Subject *<select required value={form.subject_id} onChange={e=>field('subject_id',e.target.value)}><option value="">Select subject</option>{options.subjects.map(x=><option key={x.id} value={x.id}>{x.code} - {x.name}</option>)}</select></label><label>Teacher *<select required value={form.teacher_id} onChange={e=>field('teacher_id',e.target.value)}><option value="">Select teacher</option>{options.teachers.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></label><label>Start time *<input required type="time" value={form.start_time} onChange={e=>field('start_time',e.target.value)}/></label><label>End time *<input required type="time" value={form.end_time} onChange={e=>field('end_time',e.target.value)}/></label><label className="wide">Room<input value={form.room} maxLength="80" onChange={e=>field('room',e.target.value)} placeholder="Room 12 / Science Lab"/></label></div><button className="button button-small" disabled={busy}><Save size={16}/>{busy?'Saving…':'Save period'}</button></form>}
    <section className="data-panel timetable-directory"><div className="panel-title"><div><span>Weekly schedule</span><h2>Timetable periods</h2></div><b>{rows.length} periods</b></div>{rows.length===0?<div className="empty-state"><CalendarDays/><h3>No timetable periods</h3><p>School Admin can add the first period.</p></div>:<div className="table-wrap"><table><thead><tr><th>Day & time</th><th>Class</th><th>Subject</th><th>Teacher</th><th>Room</th><th>Status</th>{canManage&&<th>Actions</th>}</tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><b>{days[row.weekday]}</b><small>{row.start_time.slice(0,5)} – {row.end_time.slice(0,5)}</small></td><td>{row.class_name}{row.section?` - ${row.section}`:''}</td><td>{row.subject_name}<small>{row.subject_code}</small></td><td>{row.teacher_name}</td><td>{row.room||'—'}</td><td><span className={`status-pill ${row.status}`}>{row.status}</span></td>{canManage&&<td><div className="student-row-actions"><button disabled={row.status!=='active'} onClick={()=>open(row)}><Edit3/>Edit</button><button className="danger" disabled={row.status!=='active'||busy} onClick={()=>archive(row)}><Trash2/>Archive</button></div></td>}</tr>)}</tbody></table></div>}</section></>
}
